### ISSUE TITLE
Dereferencing pointer as first operand of mov breaks highlighting

### ISSUE THREAD

**Issue by tj-moody** [rush-rs/tree-sitter-asm#1]
The line

```asm
    mov [ebr_drive_number], dl
```
breaks highlighting throughout the rest of the buffer, and removing the brackets fixes the issue.

I would assume that dereferencing a register and then using it as a destination for mov isn't considered valid or not considered at all, as usually it wouldn't make sense, but in this case it is valid and should be supported 

<img width="694" alt="Screenshot 2023-07-27 at 8 58 12 AM" src="https://github.com/rush-rs/tree-sitter-asm/assets/92702993/5dbe2e0f-0e26-4c65-a9ae-686b32665a36">

<img width="772" alt="Screenshot 2023-07-27 at 8 58 27 AM" src="https://github.com/rush-rs/tree-sitter-asm/assets/92702993/ca2b1116-4490-4ed9-9367-321fe0cad864">

**Comment by RubixDev** [comment]
Register names just weren't allowed to contain underscores, but that is fixed now.
